steps:
  - id: 'tf plan'
    name: 'hashicorp/terraform:1.2.6'
    entrypoint: 'sh'
    dir: "terraform/"
    args:  
      - '-c'
      - |
          echo "run init"
          terraform init
          echo "run show"
          terraform show
          echo "run plan"
          terraform plan
          echo "run apply"
          terraform apply -auto-approve

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
    - gcloud
    - functions
    - deploy
    - "${_FUNCTION_NAME}"
    - --region=europe-west1
    - --source=${_SOURCE_DIR}
    - --trigger-bucket=${_BUCKET_NAME}
    - --runtime=python310
    - --entry-point=${_ENTRY_POINT}
    # - --set-env-vars inbound_bucket_name=${_BUCKET_NAME}
options:
  logging: CLOUD_LOGGING_ONLY
  dynamic_substitutions: true

substitutions:
  _PROJECT_ID: "macro-deck-357611"
  _SOURCE_DIR: "/source"
  _FUNCTION_NAME: "cla-terraform-function-test_m1"
  _BUCKET_NAME: "macro-deck-357611-clabucket-in-test_m1_test1"
  _ENTRY_POINT: "hello_gcs"